### ISSUE TITLE
Mod crashes on New 1.18.2 Journeymap version

### ISSUE THREAD

**Issue by ModernGamingWorld** [frank89722/JourneyMapIntegration#9]
[crash-2022-03-17_11.05.24-fml.txt](https://github.com/frank89722/JourneyMapIntegration/files/8288057/crash-2022-03-17_11.05.24-fml.txt)

Currently your Mod is crashing on load up with the latest JourneyMap Update

**Comment by XFactHD** [comment]
This issue is caused by an invalid dependency declaration: https://github.com/frank89722/JourneyMapIntegration/blob/1.18.x/src/main/resources/META-INF/mods.toml#L34

If you want any version with atleast major version 5 and minor version 8, then just leave the last segment off. The comparison will always start from the left side, work segment by segment and stop when the current version doesn't fit in the range or the dependency version range doesn't specify a more specific segment.

**Comment by frank89722** [comment]
Seems like FTB mods can't work on 1.18.2 so I'll remove the 1.18.2 tag on CF for now

And this is the version for 1.18.1 with dependency version range fix 
https://www.curseforge.com/minecraft/mc-mods/journeymap-integration/files/3696674
